import type { TestCase } from "@/lib/types";
import { parseGherkinFeature, type ParsedFeatureStep } from "./feature-parser";

type GeneratePythonBddInput = {
  featureFileName: string;
  featureContent: string;
  projectName?: string;
  testCases?: TestCase[];
};

export type GeneratedPythonBddFile = {
  fileName: string;
  language: "python";
  content: string;
};

export function generatePythonBddStepDefinitions({
  featureFileName,
  featureContent,
  projectName = "QAplanet",
  testCases = []
}: GeneratePythonBddInput): GeneratedPythonBddFile {
  const parsed = parseGherkinFeature(featureContent);
  const safeFeatureFileName = sanitizeFileName(featureFileName || "generated_feature.feature", "generated_feature.feature");
  const fileName = `${slugifyFileName(parsed.title || projectName || "qaplanet")}_steps.py`;
  const steps = parsed.steps.length ? parsed.steps : fallbackStepsFromTestCases(testCases);
  const usedFunctionNames = new Map<string, number>();
  const stepDefinitions = steps.map((step) => buildStepDefinition(step, usedFunctionNames)).join("\n\n");

  return {
    fileName,
    language: "python",
    content: [
      `"""`,
      `Feature: ${escapeTripleQuoted(parsed.title)}`,
      `Step definitions for ${escapeTripleQuoted(parsed.title || projectName)}.`,
      `Generated by QAplanet.`,
      `"""`,
      "",
      "import os",
      "import re",
      "import json",
      "import logging",
      "from dataclasses import dataclass, field",
      "from pathlib import Path",
      "",
      "import pytest",
      "from pytest_bdd import scenarios, given, when, then, parsers",
      "from playwright.sync_api import Page, expect",
      "",
      "logger = logging.getLogger(\"qaplanet\")",
      "",
      "pytestmark = pytest.mark.ui",
      "",
      "THIS = Path(__file__).resolve()",
      `FEATURE_FILE = (THIS.parent / "../features/${safeFeatureFileName}").resolve()`,
      "",
      "if not FEATURE_FILE.exists():",
      "    raise FileNotFoundError(f\"Feature file not found: {FEATURE_FILE}\")",
      "",
      "scenarios(str(FEATURE_FILE))",
      "",
      "",
      "@dataclass",
      "class RuntimeContext:",
      "    data: dict = field(default_factory=dict)",
      "",
      "",
      "@pytest.fixture()",
      "def runtime_context() -> RuntimeContext:",
      "    return RuntimeContext()",
      "",
      "",
      "@pytest.fixture()",
      "def base_url() -> str:",
      "    value = os.getenv(\"QAPLANET_BASE_URL\", \"\").rstrip(\"/\")",
      "    if not value:",
      "        raise RuntimeError(\"Missing QAPLANET_BASE_URL environment variable.\")",
      "    return value",
      "",
      "",
      "@pytest.fixture()",
      "def test_user() -> str:",
      "    return os.getenv(\"QAPLANET_TEST_USER\", \"\")",
      "",
      "",
      "@pytest.fixture()",
      "def test_password() -> str:",
      "    return os.getenv(\"QAPLANET_TEST_PASSWORD\", \"\")",
      "",
      "",
      "def log_step_with_screenshot(page: Page, label: str, folder: str = \"reports\", full_page: bool = False):",
      "    # TODO: Replace with your framework screenshot helper if available.",
      "    try:",
      "        Path(folder).mkdir(parents=True, exist_ok=True)",
      "        safe_label = re.sub(r\"[^A-Za-z0-9_-]+\", \"_\", label).strip(\"_\") or \"step\"",
      "        page.screenshot(path=str(Path(folder) / f\"{safe_label}.png\"), full_page=full_page)",
      "        logger.info(\"[SCREEN-CAPTURE] %s\", label)",
      "    except Exception as exc:",
      "        logger.warning(\"Screenshot capture failed for %s: %s\", label, exc)",
      "",
      "",
      "# Step Definitions",
      stepDefinitions || "# No Gherkin steps were found in the feature file.",
      ""
    ].join("\n")
  };
}

export function buildPythonBddPackageFiles({
  featureFileName,
  featureContent,
  projectName,
  testCases = []
}: GeneratePythonBddInput) {
  const stepsFile = generatePythonBddStepDefinitions({ featureFileName, featureContent, projectName, testCases });

  return {
    featureFileName: sanitizeFileName(featureFileName || "generated_feature.feature", "generated_feature.feature"),
    featureContent,
    stepsFile,
    pageObjectFileName: "qaplanet_application_page.py",
    pageObjectContent: buildPythonPageObject(),
    testDataFileName: "test_data.json",
    testDataContent: JSON.stringify(
      {
        test_cases: testCases.map((testCase) => ({
          id: testCase.testCaseId,
          title: testCase.title ?? testCase.name,
          requirement_reference: testCase.requirementReference,
          priority: testCase.priority,
          test_type: testCase.testType ?? testCase.type
        }))
      },
      null,
      2
    ),
    configLoaderContent: buildConfigLoader(),
    stepLoggerContent: buildStepLogger(),
    pytestIniContent: buildPytestIni(),
    requirementsContent: buildRequirementsTxt(),
    readmeContent: buildPythonPackageReadme(stepsFile.fileName, sanitizeFileName(featureFileName || "generated_feature.feature", "generated_feature.feature"))
  };
}

function buildStepDefinition(step: ParsedFeatureStep, usedFunctionNames: Map<string, number>) {
  const decorator = buildDecorator(step);
  const functionName = nextFunctionName(`${step.effectiveKeyword}_${toSnakeCase(step.text)}`, usedFunctionNames);
  const params = buildFunctionParams(step);
  const body = buildStepBody(step);

  return [
    decorator,
    `def ${functionName}(${params}):`,
    `    logger.info("[STEP] ${escapePythonString(step.text)}")`,
    ...body
  ].join("\n");
}

function buildDecorator(step: ParsedFeatureStep) {
  const decoratorName = step.effectiveKeyword;
  const pattern = buildStepPattern(step.text);

  if (step.placeholders.length || /"[^"]+"/.test(step.text)) {
    return `@${decoratorName}(parsers.parse('${escapeSingleQuoted(pattern)}'))`;
  }

  return `@${decoratorName}("${escapeDoubleQuoted(step.text)}")`;
}

function buildStepPattern(text: string) {
  return text.replace(/<([A-Za-z_][A-Za-z0-9_]*)>/g, "{$1}");
}

function buildFunctionParams(step: ParsedFeatureStep) {
  const params = new Set<string>(["page: Page"]);
  if (needsBaseUrl(step.text)) {
    params.add("base_url: str");
  }
  if (step.text.toLowerCase().includes("user") || step.text.toLowerCase().includes("sign in") || step.text.toLowerCase().includes("login")) {
    params.add("test_user: str");
    params.add("test_password: str");
  }
  step.placeholders.forEach((placeholder) => params.add(`${toSnakeCase(placeholder)}: str`));
  return [...params].join(", ");
}

function buildStepBody(step: ParsedFeatureStep) {
  const text = step.text.toLowerCase();
  const screenshotLabel = toSnakeCase(step.text).slice(0, 80) || "gherkin_step";
  const notes: string[] = [];

  if (step.hasDataTable) {
    notes.push("        # TODO: pytest-bdd data table support may require a custom parser or step argument handling.");
    notes.push("        # The feature contains a data table for this step. Map table values to form/filter controls.");
  }

  if (text.includes("unauthenticated")) {
    return [
      "    try:",
      "        # TODO: Ensure user session is cleared or browser context is unauthenticated.",
      "        page.context.clear_cookies()",
      `        log_step_with_screenshot(page, "${screenshotLabel}")`,
      "    except Exception as exc:",
      `        log_step_with_screenshot(page, "${screenshotLabel}_failed")`,
      "        logger.error(\"[FAIL] Could not prepare unauthenticated context: %s\", exc)",
      "        raise"
    ];
  }

  if (needsBaseUrl(step.text) && step.effectiveKeyword === "given") {
    const path = inferPathFromStep(step.text);
    return [
      "    try:",
      `        page.goto(f"{base_url}${path}", wait_until="domcontentloaded")`,
      `        log_step_with_screenshot(page, "${screenshotLabel}")`,
      `        logger.info("[PASS] Page loaded for step: ${escapePythonString(step.text)}")`,
      "    except Exception as exc:",
      `        log_step_with_screenshot(page, "${screenshotLabel}_failed")`,
      "        logger.error(\"[FAIL] Page did not load: %s\", exc)",
      "        raise"
    ];
  }

  if (text.includes("submit") || text.includes("save") || text.includes("create") || text.includes("send")) {
    return [
      "    try:",
      ...notes,
      "        # TODO: Replace button name with the target application's accessible action name.",
      "        page.get_by_role(\"button\", name=re.compile(r\"submit|save|create|send|continue\", re.I)).click()",
      `        logger.info("[PASS] Action completed for step: ${escapePythonString(step.text)}")`,
      "    except Exception as exc:",
      `        log_step_with_screenshot(page, "${screenshotLabel}_failed")`,
      "        logger.error(\"[FAIL] Could not complete action: %s\", exc)",
      "        raise"
    ];
  }

  if (step.effectiveKeyword === "then") {
    return [
      "    try:",
      ...notes,
      "        # TODO: Replace expected text with a stable business-facing assertion.",
      "        expect(page.get_by_text(re.compile(r\"success|complete|created|saved|visible|displayed|approved|submitted\", re.I))).to_be_visible()",
      `        log_step_with_screenshot(page, "${screenshotLabel}")`,
      `        logger.info("[PASS] Assertion completed for step: ${escapePythonString(step.text)}")`,
      "    except Exception as exc:",
      `        log_step_with_screenshot(page, "${screenshotLabel}_failed")`,
      "        logger.error(\"[FAIL] Assertion failed: %s\", exc)",
      "        raise"
    ];
  }

  if (step.effectiveKeyword === "when") {
    return [
      "    try:",
      ...notes,
      "        # TODO: Implement this business action with accessible Playwright locators.",
      "        logger.info(\"[TODO] Implement action for this Gherkin step.\")",
      `        log_step_with_screenshot(page, "${screenshotLabel}")`,
      "    except Exception as exc:",
      `        log_step_with_screenshot(page, "${screenshotLabel}_failed")`,
      "        logger.error(\"[FAIL] Step action failed: %s\", exc)",
      "        raise"
    ];
  }

  return [
    "    try:",
    ...notes,
    "        # TODO: Prepare the required application state or test data for this precondition.",
    "        logger.info(\"[TODO] Implement precondition setup for this Gherkin step.\")",
    `        log_step_with_screenshot(page, "${screenshotLabel}")`,
    "    except Exception as exc:",
    `        log_step_with_screenshot(page, "${screenshotLabel}_failed")`,
    "        logger.error(\"[FAIL] Step setup failed: %s\", exc)",
    "        raise"
  ];
}

function fallbackStepsFromTestCases(testCases: TestCase[]): ParsedFeatureStep[] {
  return testCases.slice(0, 10).map((testCase) => ({
    keyword: "When",
    effectiveKeyword: "when",
    text: `the user completes ${testCase.title ?? testCase.name}`,
    placeholders: [],
    hasDataTable: false
  }));
}

function needsBaseUrl(text: string) {
  return /\b(page|navigate|opens?|visits?|portal|application|screen|dashboard|form)\b/i.test(text);
}

function inferPathFromStep(text: string) {
  const lowered = text.toLowerCase();
  if (lowered.includes("register") || lowered.includes("registration")) return "/register";
  if (lowered.includes("login") || lowered.includes("sign in")) return "/login";
  if (lowered.includes("dashboard")) return "/dashboard";
  if (lowered.includes("application")) return "/application";
  if (lowered.includes("search")) return "/search";
  return "/";
}

function nextFunctionName(baseName: string, usedFunctionNames: Map<string, number>) {
  const clean = baseName.replace(/^_+|_+$/g, "") || "step_definition";
  const count = usedFunctionNames.get(clean) ?? 0;
  usedFunctionNames.set(clean, count + 1);
  return count === 0 ? clean : `${clean}_${count + 1}`;
}

function toSnakeCase(value: string) {
  return value
    .replace(/<([^>]+)>/g, "$1")
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/^_+|_+$/g, "")
    .toLowerCase()
    .slice(0, 90);
}

function slugifyFileName(value: string) {
  return (
    value
      .toLowerCase()
      .replace(/&/g, " and ")
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 70) || "generated_feature"
  );
}

function sanitizeFileName(value: string, fallback: string) {
  const clean = value.replace(/[\\/:"*?<>|]+/g, "_").replace(/^_+|_+$/g, "");
  return clean || fallback;
}

function escapeDoubleQuoted(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function escapeSingleQuoted(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function escapePythonString(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function escapeTripleQuoted(value: string) {
  return value.replace(/"""/g, '\\"\\"\\"');
}

function buildPythonPageObject() {
  return `from playwright.sync_api import Page, expect


class QAplanetApplicationPage:
    def __init__(self, page: Page, base_url: str):
        self.page = page
        self.base_url = base_url

    def goto(self, path: str = "/"):
        self.page.goto(f"{self.base_url}{path}", wait_until="domcontentloaded")

    def submit_primary_action(self):
        # TODO: Replace with the target application's stable accessible action.
        self.page.get_by_role("button").first.click()
`;
}

function buildConfigLoader() {
  return `import os


def required_env(name: str) -> str:
    value = os.getenv(name, "")
    if not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value
`;
}

function buildStepLogger() {
  return `import logging
import re
from pathlib import Path

from playwright.sync_api import Page

logger = logging.getLogger("qaplanet")


def capture_step(page: Page, label: str, folder: str = "reports"):
    Path(folder).mkdir(parents=True, exist_ok=True)
    safe_label = re.sub(r"[^A-Za-z0-9_-]+", "_", label).strip("_") or "step"
    page.screenshot(path=str(Path(folder) / f"{safe_label}.png"), full_page=False)
    logger.info("[SCREEN-CAPTURE] %s", label)
`;
}

function buildPytestIni() {
  return `[pytest]
markers =
    smoke: smoke tests
    regression: regression tests
    ui: UI tests
    security: security tests
    accessibility: accessibility tests
    performance: performance tests
    persistent_edge: tests using persistent Edge context
`;
}

function buildRequirementsTxt() {
  return `pytest
pytest-bdd
playwright
allure-pytest
python-dotenv
`;
}

function buildPythonPackageReadme(stepFileName: string, featureFileName: string) {
  return `# QAplanet Pytest-BDD Playwright Package

Generated by QAplanet.

## Setup

1. Install dependencies:
   pip install -r requirements.txt

2. Install Playwright browsers:
   playwright install

3. Set environment variables:
   QAPLANET_BASE_URL
   QAPLANET_TEST_USER
   QAPLANET_TEST_PASSWORD

4. Run tests:
   pytest

## Included files

- features/${featureFileName}
- steps/${stepFileName}
- pages/qaplanet_application_page.py
- data/test_data.json
- utils/config_loader.py
- utils/step_logger.py
`;
}
